import { defineConfig, type PluginOption } from 'vite'
import path from 'node:path'
import { writeFileSync } from 'node:fs'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { cloudflare } from '@cloudflare/vite-plugin'

/**
 * Generate dist/_headers ở build time với CSP dynamic theo env.
 * VITE_API_URL + VITE_AUTH_CENTRAL_URL ở build time → inject vào connect-src,
 * mỗi env (dev/prod) sinh _headers khác nhau tự động.
 */
function generateHeadersPlugin(): PluginOption {
  const apiUrl = process.env.VITE_API_URL || 'https://api.nedu.vn'
  const authUrl = process.env.VITE_AUTH_CENTRAL_URL || 'https://iam.nedu.vn'
  return {
    name: 'generate-headers',
    apply: 'build',
    closeBundle() {
      const csp = [
        "default-src 'self'",
        "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com https://www.googletagmanager.com https://www.clarity.ms",
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
        "img-src 'self' data: blob: https:",
        "font-src 'self' data: https://fonts.gstatic.com",
        `connect-src 'self' ${apiUrl} ${authUrl} https://cloudflareinsights.com https://www.google-analytics.com https://*.clarity.ms`,
        "frame-ancestors 'none'",
        "base-uri 'self'",
        "form-action 'self'",
      ].join('; ')

      const headers = [
        '# Generated by vite.config.ts at build time.',
        `# API: ${apiUrl}`,
        `# Auth: ${authUrl}`,
        '',
        '/*',
        '  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload',
        '  X-Frame-Options: DENY',
        '  X-Content-Type-Options: nosniff',
        '  Referrer-Policy: strict-origin-when-cross-origin',
        '  Permissions-Policy: camera=(), microphone=(), geolocation=()',
        '  X-DNS-Prefetch-Control: off',
        `  Content-Security-Policy: ${csp}`,
        '',
        '/mockServiceWorker.js',
        '  Service-Worker-Allowed: /',
        '  Cache-Control: no-cache',
        '',
      ].join('\n')

      writeFileSync('dist/_headers', headers)
      // eslint-disable-next-line no-console
      console.log(`[generate-headers] dist/_headers written (api=${apiUrl}, auth=${authUrl})`)
    },
  }
}

export default defineConfig({
  plugins: [
    tailwindcss(),
    react(),
    cloudflare(),
    generateHeadersPlugin(),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@shared': path.resolve(__dirname, './src/shared'),
      '@modules': path.resolve(__dirname, './src/modules'),
      '@routes': path.resolve(__dirname, './src/routes'),
    },
  },
  server: {
    port: 5173,
    strictPort: false,
  },
})
